# This file was *autogenerated* from the file 11.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4)
A = Matrix(ZZ, [[_sage_const_2 ,_sage_const_1 ,_sage_const_4 ],[_sage_const_0 ,-_sage_const_1 ,_sage_const_1 ]])
B = Matrix(ZZ, [[_sage_const_1 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_1 ],[_sage_const_1 ,_sage_const_0 ]])
C = A*B
C1 = Matrix(ZZ, [_sage_const_6 ,_sage_const_3 ]) 
# First row of AB
print("First row of AB: %s" % C1)
x = vector(ZZ, [_sage_const_1 ,_sage_const_1 ])
y = vector(ZZ, [_sage_const_0 ,_sage_const_1 ])
z = vector(ZZ, [_sage_const_1 ,_sage_const_0 ])
# Linear combination of row vectors
print("Linear combination of row vectors: (%s,%s,%s)" % (_sage_const_1 ,_sage_const_2 ,_sage_const_5 ))
print("%s" % (_sage_const_1 *x + _sage_const_2 *y + _sage_const_5 *z))
